### ISSUE TITLE
setting PopUpListView styles in a custom theme causes an error

### ISSUE THREAD

**Issue by ConfidantCommunications** [feathersui/feathersui-openfl#124]
I attempted to customise the listView styles in a custom theme as described [here](https://feathersui.com/learn/haxe-openfl/pop-up-list-view/) (where it mentions setPopUpListView_ListView_Styles).
After compiling, I click the popup list and Feathers throws an error:
`Uncaught TypeError: Cannot read properties of null (reading 'layout') AdvancedLayoutViewPort.hx:305

I even left the styling function empty and the error persists.

**Comment by joshtynjala** [comment]
I just added a null check in commit eb1d550, but you'll still need to provide a layout in your custom theme.
