### ISSUE TITLE
TextInput and arabic symbols

### ISSUE THREAD

**Issue by piratejet** [feathersui/feathersui-openfl#125]
when I set embedFonts to true in the TextInput the Arabic symbols doesn't work properly, they do not reshape and don't go from right to left but if embedFonts is set to false then it works fine.

any solution, or idea on how to fix this?

thanks

**Comment by joshtynjala** [comment]
TextInput simply uses an OpenFL TextField. This is likely an issue in OpenFL, and it would need to be addressed there. For now, you'll need to use `embedFonts = false`, and try to find a "good enough" device font to use.

**Comment by piratejet** [comment]
thanks for your response.

embedFonts = false works on almost every target except android.

I tried to set another device font for android but it still is using only one default font and the Arabic reshaping and right to left direction don't work.

currently, I am trying to find a solution for android

**Comment by joshtynjala** [comment]
Closing, since this is an issue with OpenFL.
