### ISSUE TITLE
AssetLoader: maxHeight used as height when minHeight is not specified

### ISSUE THREAD

**Issue by ConfidantCommunications** [feathersui/feathersui-openfl#131]
**Issue**: I specify a maxHeight of 300 on an AssetLoader but not minHeight.
**What happens:** The AssetLoader obeys the maxHeight, but in a scaled down scenario it also uses that as the minHeight.
**What I expected**: It would use the actual content height when scaled down and minHeight not specified.
**Workaround**: Set minHeight, then it behaves as expected.

**Comment by joshtynjala** [comment]
> It would use the actual content height when scaled down and minHeight not specified.

I'm going to need a little more information to understand what's going on.

What is the actual content width and height, in this example?

When you say "scaled down", can you describe what exactly that means in terms of code?

Thanks!

**Comment by ConfidantCommunications** [comment]
Sure…Suppose actual content Bitmap "bm" is 600 pixels wide by 300 tall (2:1 ratio), going into an AssetLoader which has ResponsiveGridLayoutData. Placed in a ScrollContainer with ResponsiveGridLayout. So when I say "scaled down" I mean on a narrower screen which forces a scale of less than 100%;

I can specify:
`loader.maxHeight = bm.height;` (or alternatively 300)
On a wide 1200px screen this will display as maxHeight of 300. On a narrow screen, e.g. 400 px wide, the loader will scale to 400 wide but would be 300 tall instead of 200 pixels which would be the proper scaled-down 2:1 ratio. If I set the minHeight to 100 pixels, then the loader would use 200 pixels as the height.

**Comment by ConfidantCommunications** [comment]
For the record, the bitmap content has the correct proportions in all cases. It's just the containing AssetLoader which is too tall when minHeight is not specified.

**Comment by joshtynjala** [comment]
Okay, got it. The width is being set, and the height needs to be calculated. Normally, the height is calculated while keeping the original aspect ratio, but it's not the original aspect ratio in this case, even though the maxHeight should allow it.

Definitely not ideal. However, I recall that there was something strange that made me accept a less-than-ideal measurement for `AssetLoader`, so this could be tricky. I see that I left a comment referencing feathersui/feathersui-starling#1541. I'll need to account for that when working on a fix.

**Comment by ConfidantCommunications** [comment]
Thanks sir!

**Comment by joshtynjala** [comment]
Adding some code that reproduces with v1.0.0... in case I ever need to revisit this again in the future:

```haxe
var loader = new AssetLoader();
loader.maxWidth = 400.0;
loader.maxHeight = 400.0;
loader.addEventListener(Event.COMPLETE, event -> {
	loader.validateNow();
	trace(loader.width, loader.height); // 400, 400... but should be 200, 100
});
loader.source = "path/to/200x100.png";
container.addChild(loader);
```
