### ISSUE TITLE
[html5] default imports and macros clash

### ISSUE THREAD

**Issue by acarioni** [feathersui/feathersui-openfl#136]
**Environment**
macOS 12.6.3
haxe 4.2.5
openfl 9.2.1
feathersui 1.0.0

**Description**
When a feathersui class is imported in import.hx, macros can’t be used and the compiler throws the following error

```
~/haxe/haxelib/lime/8,0,0/src/lime/graphics/opengl/GLBuffer.hx:16: characters 20-40 : You cannot access the js package while in a macro (for js.html.webgl.Buffer)
~/haxe/haxelib/lime/8,0,0/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
~/haxe/haxelib/lime/8,0,0/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
~/haxe/haxelib/openfl/9,2,1/src/openfl/utils/ByteArray.hx:16: characters 8-26 : ... referenced here
~/haxe/haxelib/openfl/9,2,1/src/openfl/utils/IDataOutput.hx:72: characters 35-44 : ... referenced here
```

The error disappears when the default imports are commented.

**To reproduce**

```
//Main.hx
import MyClass;
class Main extends feathers.controls.Application {
  public function new() {
    super();
  }
}
//import.hx
import feathers.data.ArrayCollection;
//MyClass.hx
@:build(MyMacro.build())
class MyClass {}
//MyMacro.hx
import haxe.macro.Expr;
macro function build(): Array<Field> return null;
```

**Comment by joshtynjala** [comment]
I wasn't familiar with [import.hx](https://haxe.org/manual/type-system-import-defaults.html). Interesting oddity of Haxe.

All of the errors are in Lime or OpenFL, so I'm kind of surprised that you opened the issue for Feathers UI.

Regardless, this seems like a Haxe compiler issue. As I understand how import.hx works, the imported symbols will be imported in all files, including MyMacro.hx. In MyMacro.hx, it's probably resulting in a [macro-in-macro](https://haxe.org/manual/macro-limitations-macro-in-macro.html) situation.

**Comment by acarioni** [comment]
Thanks for your response, Josh.

I think centralizing the most used classes can be useful in Feathers applications, which require a lot of imports. Thus, even if the issue is not directly caused by Feathers, a workaround would be welcomed.

I found that wrapping the Feathers default imports inside a `#if !macro` block does the job. Maybe the same trick can be used by Feathers files to avoid the issue altogether.

**Comment by joshtynjala** [comment]
No, I think it's better for you to do that. I'm glad you found a proper workaround!
