### ISSUE TITLE
TextArea gets glitchy after a paste

### ISSUE THREAD

**Issue by hydroper** [feathersui/feathersui-openfl#137]
The new version seems to fix the scroll issue on touchpad for me. But there's regression when you paste into `TextArea`. When you paste, the next text cannot be typed at all. The paste action also doesn't always paste.

Here's the program:

```haxe
import feathers.controls.Application;
import feathers.controls.TextArea;

class HelloWorld extends Application {
	public function new() {
		super();

		var textArea = new TextArea();
		textArea.width = 300;
		textArea.height = 300;
		textArea.text = "Hello World";
		addChild(textArea);
	}
}
```

I'm running it with the command:

```plain
openfl test html5 -debug
```

Here's the output from `haxelib list`:

```plain
actuate: [1.9.0]
box2d: [1.2.3]
feathersui: 1.0.0 [1.1.0]
hxargs: [3.0.2]
hxcpp: [4.2.1]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [8.0.0]
openfl-samples: [8.7.0]
openfl: [9.2.0] 9.2.1
svg: [1.1.3]
```

**Comment by joshtynjala** [comment]
Unfortunately, I cannot reproduce this issue. I tried in Safari, Firefox, and Chrome.

**Comment by joshtynjala** [comment]
You could try OpenFL 9.2.1 and Lime 8.0.1. Maybe something was fixed.
