### ISSUE TITLE
Copy/Paste in TextInput not works reliably

### ISSUE THREAD

**Issue by rat-moonshine** [feathersui/feathersui-openfl#153]
We noticed that copy/paste texts in `feathersui.TextInput` do not works reliably at some time. 

Here are our test procedures:

1. Make sure FeathersUI/Openfl application is not running
2. Copy some texts, and paste it in a separate application to confirm
3. Open FeathersUI/Openfl application that contains a text-input component
4. Try to paste - this doesn't work
5. Try to paste in a separate application - it works
6. Copy again
7. Try to paste in FeathersUI/Openfl application - this time it works

Test environment:

Windows 10, 11
macOS Ventura
Openfl 9.3.0-Dev
Lime 8.1.0-Dev
FeathersUI [Git]

**Comment by joshtynjala** [comment]
I'm pretty sure that this is a bug in Lime's clipboard implementation on native targets.

**Comment by rat-moonshine** [comment]
Can you look into this, @joshtynjala (?) Also, do you think I create this issue in Lime repository (?)

**Comment by joshtynjala** [comment]
Yes, I'll try to get it fixed. You don't need to create a separate issue.

**Comment by joshtynjala** [comment]
openfl/lime@01a04c4d480f41973f6f26f501033e70de0d131d
