### ISSUE TITLE
ListViewEvent.ITEM_TRIGGER return as `null` to handler method when used with GroupListView

### ISSUE THREAD

**Issue by rat-moonshine** [feathersui/feathersui-openfl#156]
`ListView` unable to dispatch row-trigger event when a row is already selected, and used with `Event.CHANGE` event listener. 

The same is true for `GridView` where a row do not dispatch click event when the row is already selected and used with `Event.CHANGE` listener. In case of `GridView` we able to overcome the problem by using `GridViewEvent.CELL_TRIGGER` instead. In AIR, we could able to re-click any selected row, though. 

When applied the same listeners in case of `ListView`, the event returns as `null` when using with `ListViewEvent.ITEM_TRIGGER`. When the event triggers because of cell-trigger, the _event_ was not suppose to be _null_.

```
this.lvApplications.addEventListener(ListViewEvent.ITEM_TRIGGER, onApplicationSelected, false, 0, true);
private function onApplicationSelected(event:ListViewEvent):Void
{
        trace(event); // null
```

**Comment by joshtynjala** [comment]
I tried to reproduce with a simple case, but I was not successful.

```haxe
var listView = new ListView();
listView.dataProvider = new ArrayCollection([{text: "One"}, {text: "Two"}, {text: "Three"}]);
listView.itemToText = item -> item.text;
listView.addEventListener(ListViewEvent.ITEM_TRIGGER, onItemTrigger, false, 0, true);
addChild(listView);
```

```haxe
private function onItemTrigger(event:ListViewEvent):Void {
	trace(event);
}
```

**Comment by rat-moonshine** [comment]
Sorry, I wrongly mentioned `ListView`. It was the `GroupListView`.

**Comment by joshtynjala** [comment]
I can't seem to reproduce with `GroupListView` either.


```haxe
var groupListView = new GroupListView();
groupListView.dataProvider = new ArrayHierarchicalCollection<Dynamic>([{text: "A", children: [{text: "A-1"}, {text: "A-2"}]}], item -> item.children);
groupListView.itemToHeaderText = item -> item.text;
groupListView.itemToText = item -> item.text;
groupListView.addEventListener(GroupListViewEvent.ITEM_TRIGGER, onItemTrigger, false, 0, true);
addChild(groupListView);
```

```haxe
private function onItemTrigger(event:GroupListViewEvent):Void {
	trace(event);
}
```

**Comment by joshtynjala** [comment]
Actually, I _can_ reproduce if I use `ListViewEvent` instead of `GroupListViewEvent`. It does indeed become `null` in the listener if I use the wrong class.

With that in mind, you need to change your code to use `GroupListViewEvent` instead.

**Comment by joshtynjala** [comment]
The behavior for the wrong event type seems to depend on which target you are using. HashLink and AIR both throw exceptions when the type doesn't match. Neko and html5 both ignore that the type is wrong. hxcpp converts to null when the type is wrong (which seems similar to `Std.downcast()`).

**Comment by rat-moonshine** [comment]
Yes... I confirm I overlooked `GroupListViewEvent`. It works fine when using with it. 

Sorry, for the noise.
