### ISSUE TITLE
TextInput content can copied when displayAsPassword=true

### ISSUE THREAD

**Issue by rat-moonshine** [feathersui/feathersui-openfl#157]
Unlike AIR, a `TextInput` content can be copied using keyboard-shortcut even when its `displayAsPassword` property set to true.

```
var input = new TextInput("mypassword");
input.displayAsPassword = true;
input.editable = false;
```

**Comment by joshtynjala** [comment]
Confirmed bug in OpenFL. I'll get it fixed.

**Comment by joshtynjala** [comment]
openfl/openfl@53c2d5d5243131dfa6c1325976fa7289ff359809
