### ISSUE TITLE
Inline Label cutting off in AIR

### ISSUE THREAD

**Issue by hydroper** [feathersui/feathersui-openfl#170]
# Problem

I'm using `LetterboxScaleManager` to resize the stage to fit the window using an optimal scale ratio.

At certain scales, though, my `Label` cuts off.

![image](https://github.com/feathersui/feathersui-openfl/assets/110610266/373e70dc-ea5b-4526-b0bf-a88af94dffb0)

# Code

```as3
private function splashScreen1(): void {
    this.panel.removeChildren();
    const logo: Bitmap = new FortoresseXYImages.atelier801Logo() as Bitmap;
    logo.scaleX = logo.scaleY = 0.5;
    this.panel.addChild(logo);
    const disclaimer: Label = new Label();
    disclaimer.text = "INCLUDES ATELIER 801 PROPERTIES";
    disclaimer.variant = Label.VARIANT_HEADING;
    this.panel.addChild(disclaimer);
}
```

# Versions

**Feathers UI**: feathersui-openfl-1.2.0-as3.swc
**AIR**: 51.0 beta

**Comment by joshtynjala** [comment]
> InlineLabelCutoff.zip

The text in this demo is not cut off on my machine. Tested with AIR 50.2.4.2.
