### ISSUE TITLE
AnchorLayout: error when `relativeTo` points to something not in the layout.

### ISSUE THREAD

**Issue by player-03** [feathersui/feathersui-openfl#184]
The following code will produce an "AnchorLayout failed" error, along with an unhelpful stack trace.

```haxe
final header:Sprite = new HeaderSprite();
addChild(header);

final group:LayoutGroup = new LayoutGroup();
group.layout = new AnchorLayout();
addChild(group);

final child:FeathersControl = new FeathersControl();
child.layoutData = new AnchorLayoutData(header);
group.addChild(child);
```

It isn't hard to track down the code causing this. When `AnchorLayout` finds an item whose `relativeTo` object hasn't been laid out yet, it skips it and comes back later. But it only ever updates items in this layout, and fails if any `relativeTo` object isn't in the layout.

https://github.com/feathersui/feathersui-openfl/blob/master/src/feathers/layout/AnchorLayout.hx#L120-L123

I see two options here:

- Allow it. Change the check to `if (relativeTo != null && doneItems.indexOf(relativeTo) == -1 && items.indexOf(relativeTo) != -1)`.
- Disallow it. Update the error message to explain what might be wrong.

**Comment by player-03** [comment]
The example above can be fixed in a single line: `group.addChild(header)`. However, in more complicated cases it may not be practical to add everything to the same layout.

For example, suppose you want to set up a text field and image like this:

```
+------------+
|        text|
|        text|
|imageima    |
|geimagei    |
|mageimag    |
+------------+
```

You want the text field to take up precisely 33% of the horizontal space and 40% of the vertical, so you place it in a `HorizontalLayout` nested in a `VerticalLayout`. Then you want the image to touch exactly at the corner and fill up the rest of the screen, which `AnchorLayout` is perfect for.

Allowing this would open up possibilities, though Feathers would no longer be able to guarantee the correct order of operations. You'd have to make sure the text field is updated before the image, and swap the `addChild()` order if not.

As things stand, you could instead create a second `HorizontalLayout` for the bottom of the screen, and set the image to take up 67% of the width. This would be more robust, which is probably a good argument for keeping the restriction. Maybe I'll revisit this if I think of a use case that isn't solvable.

**Comment by player-03** [comment]
Assuming you agree, we just need better error messages. There are at least two mistakes the user could make that cause this message:

- Setting `relativeTo` to an object not in the layout.
- A circular reference, where two objects are positioned relative to one another. (Or one object relative to itself, though that's a much harder mistake to make.)

So the message might be "AnchorLayout could not resolve all relativeTo instructions. Check for circular references, and make sure relativeTo only points to objects in this layout." Or at the cost of a few more checks, we could distinguish between the two:

```haxe
if (relativeTo != null && doneItems.indexOf(relativeTo) == -1) {
	if (items.indexOf(relativeTo) == -1) {
		throw new IllegalOperationError('AnchorLayout failed: $item cannot be placed relative to $relativeTo, because the latter is not in the layout.');
	}
	continue;
}
```

**Comment by player-03** [comment]
I guess we have different ideas of how verbose error messages should be, but these get the job done.

**Comment by joshtynjala** [comment]
Typically, I like verbose error messages, but I often try to keep them shorter in Feathers UI to ensure smaller file sizes for the web. I've struggled thinking about the best way to enable more verbose error messages for development.
