### ISSUE TITLE
New Components: ActivityIndicator

### ISSUE THREAD

**Issue by joshtynjala** [feathersui/feathersui-openfl#56]
A spinning animation to indicate that some process is busy.

Not to be confused with the proposed [ProgressBar indeterminate state](https://github.com/BowlerHatLLC/feathersui-openfl/issues/35), which is different.

Example:

![animated gif](https://user-images.githubusercontent.com/141885/106789602-52823000-6607-11eb-8abe-ad534673604e.gif)

**Comment by rat-moonshine** [comment]
Do you have any updates with this addition, @joshtynjala ?
