### ISSUE TITLE
ComboBox goes blank

### ISSUE THREAD

**Issue by ConfidantCommunications** [feathersui/feathersui-openfl#68]
I discovered this issue which seems to have erupted as of beta 4. Steps to reproduce:

1. On a ComboBox with multiple items, click the box to summon the popup list.
2. Lose focus on the box by hitting escape or clicking elsewhere.
3. The field will go empty with no selection. It should instead return to the previous state it had prior to the click.

**Comment by joshtynjala** [comment]
I can reproduce the issue. Thanks!
