### ISSUE TITLE
ItemRenderer horizontal and vertical align have no effect

### ISSUE THREAD

**Issue by brighttank** [feathersui/feathersui-openfl#71]
When using the ItemRenderer the horizontalAlign and verticalAlign properties of the underlying ToggleButton can be set but they are ignored when laying out the children.

Is there any way to center text in the ItemRenderer?

**Comment by joshtynjala** [comment]
I confirm that this is a bug.

```hx
var listView = new ListView();
listView.width = 200.0;
listView.dataProvider = new ArrayCollection([{text: "One"}, {text: "Two"}, {text: "Three"}]);
listView.itemToText = item -> item.text;
listView.itemRendererRecycler = DisplayObjectRecycler.withFunction(() -> {
	var itemRenderer = new ItemRenderer();
	itemRenderer.horizontalAlign = CENTER;
	return itemRenderer;
});
addChild(listView);
```

Switching to `var itemRenderer = new ToggleButton()` aligns the text to the center correctly, so something must be broken in function that the `ItemRenderer` class overrides.

**Comment by brighttank** [comment]
Yeah, the layoutChildren method in the ItemRenderer is causing the problem.
