### ISSUE TITLE
TextInput/TextArea: option to give error state higher precedence than focus state

### ISSUE THREAD

**Issue by joshtynjala** [feathersui/feathersui-openfl#90]
Or possibly a new state that is both error and focused (which allows it have a different appearance from both states).

**Comment by MatseFR** [comment]
I like the idea of a new state for this, if the input could default to FOCUS skin if no skin is set for FOCUS+ERROR state that would prevent "breaking" anything for feathers users (even if they use a theme of their own)

**Comment by joshtynjala** [comment]
Unfortunately, a new state won't work well. It would be fine for a `TextInput` choosing values passed to `setSkinForState()`. However, it would require skin classes to have internal knowledge of `TextInput` when choosing values passed to `setFillForState()` or `setBorderForState()`. That's something I'd like to avoid.

I may try to revisit this again, though. Perhaps creating a way for `TextInput` to register fallback states with its skins could be interesting.
